Multi discrepancies
oracle/helidon pull request #2413
Opened 2020-10-06 15:17 UTC by danielkec

Signed-off-by: Daniel Kec <daniel.kec@oracle.com>

2020-10-06 16:00 UTC, olotenko requested changes

2020-10-06 19:46 UTC, spericas commented on common/reactive/src/main/java/io/helidon/common/reactive/DeferredScalarSubscription.java
> +        if ((state & REQUEST_ARRIVED) == REQUEST_ARRIVED) {
I agree that the masking in line 89 is redundant.

2020-10-06 19:58 UTC, spericas commented on common/reactive/src/main/java/io/helidon/common/reactive/MultiConcatArray.java
> +                cancel();
@olotenko To be clear, your point is that the sequence `onError onNext` is still possible as cancellation is only a best-effort task.

2020-10-06 20:20 UTC, danielkec commented on common/reactive/src/main/java/io/helidon/common/reactive/DeferredScalarSubscription.java
> +        if ((state & REQUEST_ARRIVED) == REQUEST_ARRIVED) {
Aha I see, but it makes sense in the other complete() right?
```java
    public final void complete() {
        int state = get();
        if (((state & VALUE_ARRIVED) != VALUE_ARRIVED) && compareAndSet(state, DONE)){
            downstream.onComplete();
        }
    }
```

2020-10-06 21:24 UTC, olotenko commented on common/reactive/src/main/java/io/helidon/common/reactive/DeferredScalarSubscription.java
> +        if ((state & REQUEST_ARRIVED) == REQUEST_ARRIVED) {
Yes, in the other `complete` it reflects the logic of the POC correctly: basically, in that `complete` it is "if value has not arrived yet" (was worded with different conditions with OR).

But in this `complete` the logic must be "if request has been seen, but the value still not seen" - only in that case we are allowed to deliver the signals to downstream.

2020-10-06 21:28 UTC, olotenko commented on common/reactive/src/main/java/io/helidon/common/reactive/MultiConcatArray.java
> +                cancel();
Yes, you can view this as the best effort so far. But like I mentioned offline, there is another issue that needs addressing, so we may just as well postpone touching this class.

2020-10-06 21:32 UTC, olotenko submitted a review, later dismissed
I am indifferent to the change in `MultiConcatArray`. `DeferredScalarSubscription` is good.

2020-10-07 14:52 UTC, spericas approved these changes

2020-10-07 16:28 UTC, merged