Methods contentLength and transferEncoding added
oracle/helidon pull request #2490
Opened 2020-10-29 14:06 UTC by Verdent

Fixes #2209

2020-11-03 22:01 UTC, romain-grecourt approved these changes

2020-11-09 16:36 UTC, tomas-langer requested changes

2020-11-09 16:36 UTC, tomas-langer commented on webclient/webclient/src/main/java/io/helidon/webclient/NettyClientHandler.java
> +        return headers.transferEncoding().isEmpty();
I think just checking for `isEmpty` is not sufficient. Transfer encoding can have the following values:
```
Transfer-Encoding: chunked
Transfer-Encoding: compress
Transfer-Encoding: deflate
Transfer-Encoding: gzip
Transfer-Encoding: identity
```

2020-11-10 17:40 UTC, tomas-langer approved these changes
LGTM

2020-11-11 13:08 UTC, merged