Fix instructions for enabling JSON-P for Health-Checks.
oracle/helidon pull request #2528
Opened 2020-11-16 15:40 UTC by michael-simons

2020-11-16 16:03 UTC, michael-simons commented
Just sent out the OCA.

2020-11-17 18:30 UTC, romain-grecourt commented
/trigger

2020-11-19 15:14 UTC, tomas-langer requested changes

2020-11-19 15:14 UTC, tomas-langer commented on docs/se/health/01_health.adoc
> +Declare the following dependencies in your project:
This is not needed - `helidon-health` transitively depends on `helidon-media-jsonp`

2020-11-19 15:14 UTC, tomas-langer commented on docs/se/health/01_health.adoc
> +.Enable JSON-P support on the server
This is also not needed - `HealthSupport` uses the JSON-P writer directly not to interfere with user's application choice of media types.

2020-11-19 15:16 UTC, tomas-langer commented
Hi @michael-simons, thanks for your contribution. The `HealthSupport` in current version does not require explicit registration of `JsonpSupport` with `WebServer`. You have identified an error in our documentation, the correct (new) approach is actually simpler than both the original and your updated docs. Detail in review comments

2020-11-19 15:20 UTC, michael-simons commented
A nice. I was wondering, especially about enabling the support. I didn't have this in my examples and things have been working nevertheless. I fixed my PR.

2020-11-23 12:45 UTC, tomas-langer commented
/trigger

2020-11-23 12:46 UTC, tomas-langer approved these changes

2020-11-24 20:10 UTC, merged