Documentation SE : Webclient guide
oracle/helidon pull request #3189
Opened 2021-07-14 09:21 UTC by tvallin

2021-10-06 12:50 UTC, Verdent requested changes
Please take a look at possible changes here. :-)

2021-10-06 12:50 UTC, Verdent commented on docs/se/guides/40_webclient.adoc
> +which contains response code, headers and non-handled entity.
Received response entity will be automatically handled as a `String`. If no specific type is put into the method `request()`, `WebClientResponse` is returned by default. This `WebClientResponse` object contains response code, headers and non-handled entity.

2021-10-06 12:50 UTC, Verdent commented on docs/se/guides/40_webclient.adoc
> +In the Uri, the string after `greet` is a path parameter which allows the application to greet someone.
String

2021-10-06 12:50 UTC, Verdent commented on docs/se/guides/40_webclient.adoc
> +<2> Execute a PUT request.
Create
You are executing the PUT request with the submit. Now you are just creating it.

2021-10-06 12:50 UTC, Verdent commented on docs/se/guides/40_webclient.adoc
> +This time, we use the put and submit methods to push the new greeting. One way to check the greeting modification
This time, we use the PUT request

2021-10-06 12:50 UTC, Verdent commented on docs/se/guides/40_webclient.adoc
> +is to get greeting and display it to the console. `thenCompose` method will execute a GET request after
is to execute GET request again and display obtained response.

2021-10-06 12:50 UTC, Verdent commented on docs/se/guides/40_webclient.adoc
> +comment can be used. The `methods` will target the Http request type of your choice. `success` and `error` will
can be used -> are not required to be used

2021-10-08 07:19 UTC, tvallin commented
@Verdent thanks for your review, I applied the required changes.

2021-11-04 17:38 UTC, Verdent submitted a review, later dismissed
LGTM

2021-11-15 16:17 UTC, ljamen reviewed
Let me know if you have any questions about my comments.

2021-11-15 16:17 UTC, ljamen commented on docs/se/guides/40_webclient.adoc
> +In practice, String is not the most useful return type, since it usually needs some more handling.In this case it could
since it usually requires additional handling. (space missing) In this case it could

2021-11-15 16:17 UTC, ljamen commented on docs/se/guides/40_webclient.adoc
> +be more interesting to return an object such as JsonObject. Earlier, Json support was added to the webclient,
In the previous step JSON support was added to the WebClient so that it could be used instead of String.

2021-11-15 16:17 UTC, ljamen commented on docs/se/guides/40_webclient.adoc
> +In the Uri, the String following `greet` is a path parameter which allows the application to greet someone.
URI

2021-11-15 16:17 UTC, ljamen commented on docs/se/guides/40_webclient.adoc
> +request to `/greet/greeting` endpoint from the base Uri.
URI

2021-11-15 16:17 UTC, ljamen commented on docs/se/guides/40_webclient.adoc
> +According to the quickstart documentation, a Json object can be sent to the application to change the greeting following
JSON

2021-11-15 16:17 UTC, ljamen commented on docs/se/guides/40_webclient.adoc
> +the PUT request is executed.
The `thenCompose` method will

2021-11-15 16:17 UTC, ljamen commented on docs/se/guides/40_webclient.adoc
> +WebClient as other Helidon components support Metrics. This chapter introduces the different metrics usable to measure
WebClient, like other Helidon components, supports Metrics. The following example introduces the different metrics that can be used to measure WebClient activity. There are two ways to set up metrics: programmatically on the WebClient instance or manually using the configuration file.

2021-11-15 16:17 UTC, ljamen commented on docs/se/guides/40_webclient.adoc
> +There is a specific dependency to use web client metrics in your application.
WebClient

2021-11-15 16:17 UTC, ljamen commented on docs/se/guides/40_webclient.adoc
> +It is possible to register metrics on WebClient directly into the code. Will be described a general method to use with
It is possible to register metrics on WebClient directly into the code. The following example shows a general method that can be used with any metric.

2021-11-15 16:17 UTC, ljamen commented on docs/se/guides/40_webclient.adoc
> +<3> Build a Web Client Service for counting the GET requests.
WebClient

2021-11-15 16:17 UTC, ljamen commented on docs/se/guides/40_webclient.adoc
> +In order to pass this information to the webclient, the `nameFormat` method extracts it from the metric name.
WebClient

2021-11-15 16:17 UTC, ljamen commented on docs/se/guides/40_webclient.adoc
> +comment are not required to be used. The `methods` will target the Http request type of your choice. `success` and `error` will
The `methods` will target the chosen HTTP request type. while `success`and `error` will respectively measure if a request is successful or failed. The `description` will add a metric description.

2021-11-15 16:17 UTC, ljamen commented on docs/se/guides/40_webclient.adoc
> +Using configuration file can reduce the code complexity and makes the metrics simpler to use. There is no
Using the configuration file can reduce the code complexity and make the metrics simpler to use.

2021-11-15 16:17 UTC, ljamen commented on docs/se/guides/40_webclient.adoc
> +As shown, using configuration file strongly reduces the amount of code needed in the source code. If you want more
WebClient

As demonstrated, using the configuration file reduces the amount of code needed in the source code. For more information about metrics, see the <<se/guides/05_metrics.adoc,Helidon Metrics Guide>>.

2021-11-16 09:25 UTC, tvallin commented
Thank you @ljamen, I applied the changes.

2021-11-16 09:44 UTC, Verdent approved these changes

2021-11-16 13:39 UTC, merged