Defer writes with backpressure #3684
oracle/helidon pull request #3729
Opened 2021-12-13 16:25 UTC by danielkec

Fixes #3684

Signed-off-by: Daniel Kec <daniel.kec@oracle.com>

2021-12-15 08:43 UTC, danielkec commented
There doesn't seems to be any obvious perf degradation
![image](https://user-images.githubusercontent.com/1773630/146152966-29a63792-a23a-4de4-a91f-b7f8439483c6.png)

2021-12-20 17:40 UTC, tomas-langer approved these changes
LGTM, but please get at least one other review

2021-12-21 07:21 UTC, dalexandrov approved these changes

2021-12-21 15:05 UTC, Verdent requested changes

2021-12-21 15:05 UTC, Verdent commented on webserver/webserver/src/main/java/io/helidon/webserver/BareResponseImpl.java
> +            writeLastContent(throwable, ChannelFutureListener.CLOSE_ON_FAILURE);
If closing connection which has been asked by client to be kept alive, this would not close it.

2022-02-07 11:55 UTC, danielkec commented
Closing in favor of #3830 and #3866

2022-02-07 11:55 UTC, closed without merging