DOC: JBatch guide for issue 2785
oracle/helidon pull request #3895
Opened 2022-02-14 20:40 UTC by ljamen

Replaces PR #3596 for JBatch documentation.

2022-03-02 10:02 UTC, dalexandrov requested changes
Hello Lisa, 
there were some changes in the JBatch example. I have requested changes to the guide to follow those changes. Could you be so kind to apply them :)

Thank you :)

2022-03-02 10:02 UTC, dalexandrov commented on docs/mp/guides/39_jbatch.adoc
> +
Please add the following:

To check job status, simply call:

[source,bash]
----
 curl -X GET http://localhost:8080/batch/status/1 (1)
----
(1) Job Id may differ.

and you should see the following output:

[source,bash]
----
{"Steps executed":"[step1, step2]","Status":"COMPLETED"}
----

2022-03-03 15:56 UTC, ljamen commented on docs/mp/guides/39_jbatch.adoc
> +----
@dalexandrov Do you have the complete code example in your examples file? I think there may be a copy paste issue with this example. I want to take it directly from your source.

2022-03-07 18:51 UTC, dalexandrov commented
Hello Lisa,
this is the full example: https://github.com/oracle/helidon/tree/helidon-2.x/examples/jbatch

2022-03-09 17:50 UTC, dalexandrov requested changes

2022-03-09 17:50 UTC, dalexandrov commented on docs/mp/guides/39_jbatch.adoc
> +        public MyInputRecord(int id) {
Please fix Indentation

2022-03-09 17:50 UTC, dalexandrov commented on docs/mp/guides/39_jbatch.adoc
> +public class HelidonExecutorServiceProvider implements ExecutorServiceProvider {
Please fix the indentation

2022-03-09 20:01 UTC, dalexandrov commented on docs/mp/guides/39_jbatch.adoc
> +public class HelidonExecutorServiceProvider implements ExecutorServiceProvider {
Should be:

```
public class HelidonExecutorServiceProvider implements ExecutorServiceProvider {
    @Override
    public ExecutorService getExecutorService() {
        return ThreadPoolSupplier.builder().corePoolSize(2).build().get();
    }
}
```

2022-03-09 20:05 UTC, dalexandrov requested changes

2022-03-09 20:05 UTC, dalexandrov commented on docs/mp/guides/39_jbatch.adoc
> +public class HelidonExecutorServiceProvider implements ExecutorServiceProvider {
Should be:

```
public class HelidonExecutorServiceProvider implements ExecutorServiceProvider {
    @Override
    public ExecutorService getExecutorService() {
        return ThreadPoolSupplier.builder().corePoolSize(2).build().get();
    }
}
```

2022-03-10 08:02 UTC, dalexandrov approved these changes

2022-03-10 08:02 UTC, merged