Updated doc for FT MP using new template
oracle/helidon pull request #4438
Opened 2022-06-27 18:33 UTC by spericas

Updated doc for FT MP using new template.

Signed-off-by: Santiago Pericasgeertsen <santiago.pericasgeertsen@oracle.com>

2022-06-27 18:48 UTC, ljamen reviewed
LGTM - note to myself for review.

2022-06-27 18:48 UTC, ljamen commented on docs/mp/faulttolerance/01_overview.adoc
> +The MicroProfile Fault Tolerance specification defines a set of annotations to decorate
No action, note from LJ: Using https://github.com/eclipse/microprofile-fault-tolerance/blob/master/spec/src/main/asciidoc/microprofile-fault-tolerance-spec.asciidoc

2022-06-28 14:18 UTC, dalexandrov submitted a review, later dismissed
LGTM, just few minor fixes :)

2022-06-28 14:18 UTC, dalexandrov commented on docs/mp/faulttolerance/01_overview.adoc
> +----
Do we have examples in the code? If yes, pleas add a link.

2022-06-28 14:18 UTC, dalexandrov commented on docs/mp/faulttolerance/01_overview.adoc
> +* link:{fault-tolerance-se}[Fault Tolerance in Helidon SE]
I don't think we need this here, since this doc is for Helidon MP

2022-06-28 14:18 UTC, dalexandrov commented on docs/mp/faulttolerance/01_overview.adoc
> +== Reference
Please add link to JavaDoc

2022-06-28 23:23 UTC, tjquinno requested changes
Looks good except for one broken link.

2022-06-28 23:23 UTC, tjquinno commented on docs/mp/faulttolerance/01_overview.adoc
> +* link:{fault-tolerance-spec-url}}[MicroProfile Fault Tolerance]
At least as rendered when viewing the file on GitHub, this link is broken. Looks like maybe the double `}` after the URL?

2022-06-29 14:45 UTC, ljamen reviewed
Small updates. 
Change to `half-open state` throughout.

2022-06-29 14:45 UTC, ljamen commented on docs/mp/faulttolerance/01_overview.adoc
> +to open the circuit  breaker after 4 or more failures occur in that window, and to transition
extra space circuit breaker

2022-06-29 14:45 UTC, ljamen commented on docs/mp/faulttolerance/01_overview.adoc
> +back to half open state after 3 consecutive and successful runs. Additionally, it sets an overall timeout
half-open state

2022-06-29 15:03 UTC, tjquinno approved these changes

2022-06-29 17:41 UTC, merged