Fix all copyright warnings.
oracle/helidon pull request #4660
Opened 2022-08-02 21:53 UTC by tomas-langer

Fix all copyright warnings. The plugin will be modified to fail on wrong number of lines of a copyright.
Kindly update you templates!

2022-08-02 23:01 UTC, tjquinno requested changes
There are formatting issues with some files. Please see notes.

2022-08-03 11:25 UTC, tomas-langer commented on jersey/client/src/main/java/io/helidon/jersey/client/ClientBuilderListener.java
I have done a search and replace that probably did that (and caused some of the formatting failures). I will revisit the modified files (and fix the end of lines in all of them)

2022-08-03 11:27 UTC, tomas-langer commented on examples/microprofile/bean-validation/src/test/java/io/helidon/tests/integration/bean/validation/TestValidationEndpoint.java
> + */package io.helidon.tests.integration.bean.validation;
Should be now fixed in all of them.

2022-08-03 11:49 UTC, tomas-langer commented on jersey/client/src/main/java/io/helidon/jersey/client/ClientBuilderListener.java
I will not fix the extra blank page (or lack thereof), as that impacts hundreds of files (and is not validated anyway).

2022-08-03 12:02 UTC, tjquinno approved these changes

2022-08-03 12:09 UTC, danielkec approved these changes

2022-08-03 16:22 UTC, merged