Round Robin added as DNS resolver option
oracle/helidon pull request #4798
Opened 2022-08-25 13:20 UTC by Verdent

Fixes #4744

2022-08-25 13:37 UTC, tomas-langer requested changes
This brings a new dependency.
What is the size?

2022-08-25 13:37 UTC, tomas-langer commented on webclient/webclient/src/main/java/io/helidon/webclient/WebClientConfiguration.java
> +        public DnsResolverType dnsResolverType;
Should be private

2022-08-25 14:19 UTC, Verdent commented
New dependency is `netty-resolver-dns` which brings along `netty-codec-dns`.

Complete size is: 217 kb

2022-08-26 12:22 UTC, tomas-langer approved these changes

2022-08-26 15:12 UTC, barchetta approved these changes

2022-08-29 07:55 UTC, merged